### ISSUE TITLE
Dunno how to OvR

### ISSUE THREAD

**Issue by Mokui** [ynov-ml/ML-2019#34]
@JeffAbrahamson Have you a documented example? 
I don't understand the logic used so i didn't done it yet

**Comment by JeffAbrahamson** [comment]
What did you try?  Have you been banging your head against this for the last month or are you first looking at it today?
What _do_ you understand?

With whom else did you talk trying to solve this?

**Comment by JeffAbrahamson** [comment]
I'm closing this.  This should be an issue against your own code, with me and whoever else you've asked for help tagged, so that we can follow and evolve your answer.
